version : '3'

services:
    lb:
        image: haproxy
        container_name: haproxy
        ports:
            - "8080:8080"
        volumes:
            - ./haproxy:/usr/local/etc/haproxy
    ws1:
        container_name: ws1
        image: wsapp
        environment:
            - APPID=1111
    ws2:
        container_name: ws2
        image: wsapp
        environment:
            - APPID=2222
    ws3:
        container_name: ws3
        image: wsapp
        environment:
            - APPID=3333
    ws4:
        container_name: ws4
        image: wsapp
        environment:
            - APPID=4444
    rds:
        container_name: redis-chat
        image: redis